import { Product, Order, Review } from './types';

export const CATEGORIES = [
  { id: 'all', name: 'All Delights', arabicName: 'كل اللذائذ' },
  { id: 'coffee', name: 'Signature Coffee', arabicName: 'قهوة مميزة' },
  { id: 'sweets', name: 'Gourmet Donuts', arabicName: 'دونات فاخرة' },
  { id: 'bakery', name: 'Warm Bakery', arabicName: 'مخبوزات دافئة' },
  { id: 'specialty', name: 'Specialty Drinks', arabicName: 'مشروبات خاصة' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'donut-1',
    name: 'Signature Chocolate Donut',
    arabicName: 'دونات الشوكولاتة المميزة',
    description: 'A masterpiece of soft brioche dough hand-dipped in rich Belgian dark chocolate ganache, finished with a delicate dusting of gold leaf and crunchy cacao nibs.',
    arabicDescription: 'تحفة فنية من عجينة البريوش الهشة المغطسة يدوياً بجاناش الشوكولاتة البلجيكية الداكنة والغنية، ومزينة بلمسة رقيقة من ورق الذهب ورقائق الكاكاو المقرمشة.',
    price: 4.50,
    rating: 4.9,
    reviewCount: 124,
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&q=80&w=800',
    category: 'sweets',
    tags: ['Best Seller', 'Belgian Chocolate', 'Handcrafted'],
    isPopular: true,
    calories: 380,
    ingredients: ['Brioche flour', 'Belgian dark chocolate (72%)', 'Organic butter', 'Cacao nibs', '24k gold leaf flakes'],
    deliveryTime: '15-25 mins',
    sizes: ['Single Piece', 'Box of 6 (Save 10%)', 'Box of 12 (Save 15%)'],
  },
  {
    id: 'donut-2',
    name: 'Pistachio Dream Donut',
    arabicName: 'دونات حلم الفستق',
    description: 'Filled with velvety house-made Iranian pistachio cream, topped with a gorgeous white chocolate pistachio drizzle and crushed premium pistachios.',
    arabicDescription: 'محشوة بكريمة الفستق الإيراني المخملية والمحضرة منزلياً، تعلوها خيوط الشوكولاتة البيضاء اللذيذة بالفستق وحبات الفستق الفاخرة المطحونة.',
    price: 5.00,
    rating: 4.8,
    reviewCount: 96,
    image: 'https://images.unsplash.com/photo-1612240498936-65f5101365d2?auto=format&fit=crop&q=80&w=800',
    category: 'sweets',
    tags: ['Trending', 'Pistachio Cream'],
    isPopular: true,
    calories: 410,
    ingredients: ['Iranian pistachio paste', 'White chocolate', 'Vanilla bean', 'Organic milk', 'Brioche dough'],
    deliveryTime: '15-25 mins',
    sizes: ['Single Piece', 'Box of 6', 'Box of 12'],
  },
  {
    id: 'donut-3',
    name: 'Rose & Cardamom Glazed',
    arabicName: 'دونات مغطاة بالورد والهيل',
    description: 'A sensory journey featuring a subtle, sweet glaze infused with organic cardamom pods and natural rose water, sprinkled with edible rose petals.',
    arabicDescription: 'رحلة حسية تتميز بغلاف سكري خفيف غني بحبات الهيل العضوية وماء الورد الطبيعي، مع رشة من بتلات الورد الصالحة للأكل.',
    price: 4.25,
    rating: 4.7,
    reviewCount: 54,
    image: 'https://images.unsplash.com/photo-1533930479130-194177744bcb?auto=format&fit=crop&q=80&w=800',
    category: 'sweets',
    tags: ['Floral', 'Spiced'],
    calories: 320,
    ingredients: ['Rose water infusion', 'Ground cardamom', 'Organic cane sugar', 'Pure butter glaze'],
    deliveryTime: '20-30 mins',
    sizes: ['Single Piece', 'Box of 6', 'Box of 12'],
  },
  {
    id: 'coffee-1',
    name: 'Classic Spanish Latte',
    arabicName: 'سبانش لاتيه كلاسيك',
    description: 'Premium double-shot espresso brewed from Ethiopian coffee beans, perfectly balanced with sweet condensed milk and textured velvety microfoam.',
    arabicDescription: 'جرعة مزدوجة من إسبريسو حبوب القهوة الإثيوبية الفاخرة، متوازنة تماماً مع الحليب المكثف المحلى ورغوة الحليب المخملية الدقيقة.',
    price: 5.50,
    rating: 4.9,
    reviewCount: 210,
    image: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=800',
    category: 'coffee',
    tags: ['Award Winning', 'Ethiopian Beans', 'Bestseller'],
    isPopular: true,
    calories: 220,
    ingredients: ['Double shot espresso', 'Sweetened condensed milk', 'Organic whole milk'],
    deliveryTime: '10-15 mins',
    sizes: ['Regular (12oz)', 'Large (16oz)'],
  },
  {
    id: 'coffee-2',
    name: 'Saffron Cloud Cold Brew',
    arabicName: 'كولد برو سحابة الزعفران',
    description: 'Our slow-dripped 18-hour cold brew topped with a luxurious, airy cold foam infused with real Kashmiri saffron threads and a hint of wildflower honey.',
    arabicDescription: 'قهوة باردة مقطرة ببطء لمدة 18 ساعة تعلوها رغوة باردة هشة وفاخرة غنية بخيوط الزعفران الكشميري الأصيل ولمسة من عسل زهر البري.',
    price: 6.25,
    rating: 4.9,
    reviewCount: 88,
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&q=80&w=800',
    category: 'coffee',
    tags: ['Premium', 'Cold Brew', 'Local Favorite'],
    isPopular: true,
    calories: 140,
    ingredients: ['18-hour cold brew', 'Kashmiri saffron threads', 'Skimmed milk cold foam', 'Wildflower honey'],
    deliveryTime: '10-15 mins',
    sizes: ['Regular (12oz)', 'Large (16oz)'],
  },
  {
    id: 'coffee-3',
    name: 'Salted Caramel Macchiato',
    arabicName: 'ماكياتو الكراميل المملح',
    description: 'Rich, full-bodied espresso marked with steamed milk and a generous, artistic swirl of our artisan house-made salty caramel sauce.',
    arabicDescription: 'إسبريسو غني وقوي مع حليب ساخن ورشة فنية سخية من صلصة الكراميل المملح المحضرة يدوياً في متجرنا.',
    price: 5.75,
    rating: 4.6,
    reviewCount: 142,
    image: 'https://images.unsplash.com/photo-1485808191679-5f86510681a2?auto=format&fit=crop&q=80&w=800',
    category: 'coffee',
    tags: ['Sweet', 'Rich'],
    calories: 260,
    ingredients: ['Signature Espresso roast', 'Steamed whole milk', 'House-made salted caramel sauce'],
    deliveryTime: '10-15 mins',
    sizes: ['Regular (12oz)', 'Large (16oz)'],
  },
  {
    id: 'bakery-1',
    name: 'Flaky Almond Croissant',
    arabicName: 'كرواسون اللوز الهش',
    description: 'Double-baked, buttery Parisian style layers filled with rich sweet almond frangipane cream, topped with roasted sliced almonds and snow-white powdered sugar.',
    arabicDescription: 'كرواسون مخبوز مرتين على الطريقة الباريسية الهشة والغنية بالزبدة، محشو بكريمة اللوز الحلوة (فرانجيبان)، ومغطى باللوز المحمص ورقائق السكر الأبيض الناعم.',
    price: 4.75,
    rating: 4.8,
    reviewCount: 115,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
    category: 'bakery',
    tags: ['Butter rich', 'Oven Fresh'],
    calories: 440,
    ingredients: ['French butter (AOP)', 'Almond frangipane', 'Flaked almonds', 'Unbleached flour'],
    deliveryTime: '15-20 mins',
    sizes: ['Single Piece', 'Box of 4', 'Box of 8'],
  },
  {
    id: 'bakery-2',
    name: 'Pecan & Cinnamon Roll',
    arabicName: 'لفافة القرفة والبيكان',
    description: 'Fluffy, golden brioche roll swirled with high-grade Ceylon cinnamon and dark brown sugar, frosted with cream cheese glaze and toasted Texas pecans.',
    arabicDescription: 'لفافة بريوش ذهبية وهشة محشوة بقرفة سيلان الفاخرة والسكر البني الداكن، مغطاة بصلصة جبنة الكريمة وحبات بيكان تكساس المحمصة.',
    price: 4.95,
    rating: 4.7,
    reviewCount: 84,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
    category: 'bakery',
    tags: ['Sweet & Spiced', 'Oven Fresh'],
    calories: 490,
    ingredients: ['Brioche dough', 'Ceylon cinnamon', 'Maple cream cheese glaze', 'Toasted pecans'],
    deliveryTime: '15-20 mins',
    sizes: ['Single Piece', 'Pair', 'Box of 4'],
  },
  {
    id: 'specialty-1',
    name: 'Ceremonial Matcha Latte',
    arabicName: 'ماتشا لاتيه الاحتفالية',
    description: 'Finest hand-whisked Uji stone-ground ceremonial matcha combined with velvety steamed oat milk and a touch of organic maple syrup.',
    arabicDescription: 'أجود أنواع الماتشا الاحتفالية المطحونة على الحجر من مدينة أوجي اليابانية، مخفوقة يدوياً وممزوجة بحليب الشوفان الساخن والمخملي مع لمسة من شراب القيقب العضوي.',
    price: 6.00,
    rating: 4.8,
    reviewCount: 138,
    image: 'https://images.unsplash.com/photo-1594911774802-8822a707cff3?auto=format&fit=crop&q=80&w=800',
    category: 'specialty',
    tags: ['Antioxidant', 'Japanese Import', 'Oat Milk'],
    calories: 120,
    ingredients: ['Ceremonial Matcha from Uji', 'Steamed Oatly milk', 'Organic pure maple syrup'],
    deliveryTime: '10-15 mins',
    sizes: ['Regular (12oz)', 'Large (16oz)'],
  }
];

export const REVIEWS: Review[] = [
  {
    id: 'r1',
    userName: 'Layla Al-Mansour',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150',
    rating: 5,
    comment: 'The Signature Chocolate Donut is absolute perfection. Soft, rich, and not overly sweet. It paired amazingly with the Saffron Cold Brew!',
    arabicComment: 'دونات الشوكولاتة المميزة تفوق الوصف! هشة وغنية وحلاوتها متوازنة تماماً. تناغمها رائع مع الكولد برو بالزعفران!',
    date: 'July 1, 2026',
    productName: 'Signature Chocolate Donut',
  },
  {
    id: 'r2',
    userName: 'Khalid Abdullah',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150',
    rating: 5,
    comment: 'The best Spanish Latte in town! The espresso has deep floral notes that match beautifully with the condensed milk. Will definitely order again.',
    arabicComment: 'أفضل سبانش لاتيه في المدينة! الإسبريسو له نكهات زهرية عميقة تتكامل بجمال مع الحليب المكثف. سأكرر الطلب بالتأكيد.',
    date: 'June 30, 2026',
    productName: 'Classic Spanish Latte',
  },
  {
    id: 'r3',
    userName: 'Sarah Smith',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150',
    rating: 4,
    comment: 'Delicious pistachio donut, filled to the brim with cream. Extremely fresh!',
    arabicComment: 'دونات الفستق لذيذة للغاية، ومحشوة بالكامل بالكريمة. طازجة جداً!',
    date: 'June 28, 2026',
    productName: 'Pistachio Dream Donut',
  }
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-8924',
    customerName: 'Aisha Al-Subaie',
    customerEmail: 'aisha.subaie@example.com',
    items: [
      { productName: 'Signature Chocolate Donut', quantity: 2, size: 'Single Piece', price: 4.50 },
      { productName: 'Classic Spanish Latte', quantity: 1, size: 'Regular (12oz)', price: 5.50 },
    ],
    totalAmount: 14.50,
    status: 'Delivered',
    date: '2026-07-01',
    shippingAddress: 'Yas Island, Al Diyafah St, Villa 42, Abu Dhabi',
    paymentMethod: 'Apple Pay',
  },
  {
    id: 'ORD-8923',
    customerName: 'Yousef Al-Harbi',
    customerEmail: 'yousef.h@example.com',
    items: [
      { productName: 'Pistachio Dream Donut', quantity: 1, size: 'Single Piece', price: 5.00 },
      { productName: 'Saffron Cloud Cold Brew', quantity: 2, size: 'Large (16oz)', price: 6.25 },
    ],
    totalAmount: 17.50,
    status: 'Preparing',
    date: '2026-07-01',
    shippingAddress: 'Downtown Dubai, Boulevard Heights, Apt 1402, Dubai',
    paymentMethod: 'Credit Card (Visa)',
  },
  {
    id: 'ORD-8922',
    customerName: 'Fahad Al-Qahtani',
    customerEmail: 'fahad.q@example.com',
    items: [
      { productName: 'Flaky Almond Croissant', quantity: 3, size: 'Single Piece', price: 4.75 },
    ],
    totalAmount: 14.25,
    status: 'Pending',
    date: '2026-06-30',
    shippingAddress: 'Al Olaya, Olaya Towers Tower B, Riyadh',
    paymentMethod: 'Cash on Delivery',
  }
];

export const PROMO_CODES = [
  { code: 'SWEET10', discount: 0.10, description: '10% off your total purchase' },
  { code: 'COFFEEFREE', discount: 5.00, description: 'Flat $5.00 off orders over $15.00' },
  { code: 'WELCOME', discount: 0.15, description: '15% off first order for sweet members' }
];
